worker_processes 2;
events { worker_connections 1024; }

http {
    include mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    gzip on;
    gzip_types text/css application/javascript application/json;

    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass http://gateway:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /comic/hq/ {
            alias /manga/hq/;
            expires 60d;
        }

        location /comic/lq/ {
            alias /manga/lq/;
            try_files $uri @lq_not_found;
            expires 30d;
        }

        location @lq_not_found { return 204; }

        location /comic/thumbs/ {
            alias /manga/thumbs/;
            expires 7d;
        }
    }
}
