server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  application:
    name: comic-gateway
  codec:
    max-in-memory-size: 32MB
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:localhost:8848}
        username: ${NACOS_USER:}
        password: ${NACOS_PASS:}
      config:
        import-check:
          enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: api-service
          uri: lb://comic-api-service
          predicates:
            - Path=/api/**
